INSERT INTO public.menu_items (name, description, price, category_id, is_available)
SELECT i.name, i.description, i.price, c.id, true
FROM (VALUES
('Cold Coffee','Chilled coffee with milk',80.00,'Beverages'),
('Iced Tea','Refreshing lemon iced tea',60.00,'Beverages'),
('Lemonade','Fresh squeezed lemonade',50.00,'Beverages'),
('Mango Shake','Thick mango milkshake',90.00,'Beverages'),
('Sweet Lassi','Chilled sweet yoghurt drink',70.00,'Beverages'),
('Cold Brew','Slow steeped cold brew coffee',100.00,'Beverages'),
('Masala Chaas','Spiced buttermilk',50.00,'Beverages'),
('Fruit Punch','Mixed fruit punch',80.00,'Beverages'),
('Masala Chai','Spiced Indian tea',30.00,'Hot Drinks'),
('Filter Coffee','South Indian filter coffee',60.00,'Hot Drinks'),
('Hot Chocolate','Rich creamy hot chocolate',80.00,'Hot Drinks'),
('Green Tea','Light and refreshing green tea',40.00,'Hot Drinks'),
('Cappuccino','Espresso with steamed milk foam',90.00,'Hot Drinks'),
('Samosa (2 pcs)','Crispy potato filled samosas',40.00,'Snacks'),
('Vada Pav','Mumbai style vada pav',35.00,'Snacks'),
('Veg Sandwich','Grilled vegetable sandwich',70.00,'Snacks'),
('Paneer Roll','Paneer tikka in a wrap',80.00,'Snacks'),
('French Fries','Salted crispy fries',90.00,'Snacks'),
('Bread Pakora','Stuffed bread fritters',50.00,'Snacks'),
('Aloo Tikki','Spiced potato patties',45.00,'Snacks'),
('Nachos','Corn chips with salsa and cheese',100.00,'Snacks'),
('Spring Roll','Crispy vegetable spring rolls',80.00,'Snacks'),
('Poha','Light flattened rice snack',50.00,'Snacks'),
('Rajma Chawal','Kidney bean curry with rice',120.00,'Meals'),
('Chole Chawal','Chickpea curry with rice',120.00,'Meals'),
('Dal Makhani Thali','Dal makhani with 2 rotis',130.00,'Meals'),
('Veg Thali','Full vegetarian thali',150.00,'Meals'),
('Paneer Masala','Paneer butter masala with roti',160.00,'Meals'),
('Veg Fried Rice','Wok tossed vegetable fried rice',130.00,'Meals'),
('Hakka Noodles','Chinese style hakka noodles',120.00,'Meals'),
('Veg Biryani','Fragrant vegetable biryani',150.00,'Meals'),
('Gulab Jamun','2 pieces of gulab jamun',60.00,'Desserts'),
('Ice Cream','Vanilla or chocolate scoop',70.00,'Desserts'),
('Brownie','Warm chocolate fudge brownie',90.00,'Desserts'),
('Jalebi','Crispy sweet jalebi',50.00,'Desserts'),
('Kheer','Creamy rice pudding',60.00,'Desserts'),
('Chai + Samosa','Masala chai with 2 samosas',60.00,'Combos'),
('Vada Pav + Lassi','Vada pav with sweet lassi',95.00,'Combos'),
('Meal + Cold Coffee','Any meal with a cold coffee',190.00,'Combos'),
('Snack Box','3 assorted snack items',120.00,'Combos')
) AS i(name, description, price, category_name)
JOIN public.categories c ON c.name = i.category_name
ON CONFLICT DO NOTHING;
